export const regionList = [
    {
      mainArea: "Abşeron r.",
      parts: [
        "Ceyranbatan",
        "Çiçək",
        "Digah",
        "Fatmayı",
        "Görədil",
        "Hökməli",
        "Köhnə Corat",
        "Qobu",
        "Masazır",
        "Mehdiabad",
        "Məmmədli",
        "Novxanı",
        "Pirəkəşkül",
        "Saray",
        "Yeni Corat",
        "Zağulba",
        "Xırdalan",
      ],
    },
    {
      mainArea: "Binəqədi r.",
      parts: [
        "2-ci Alatava",
        "28 May",
        "6-cı mikrorayon",
        "7-ci mikrorayon",
        "8-ci mikrorayon",
        "9-cu mikrorayon",
        "Biləcəri",
        "Binəqədi",
        "Xocəsən",
        "Xutor",
        "M.Ə.Rəsulzadə",
        "Sulutəpə",
      ],
    },
    {
      mainArea: "Xətai r.",
      parts: ["Ağ şəhər", "Əhmədli", "Həzi Aslanov", "Köhnə Günəşli", "NZS"],
    },
    {
      mainArea: "Xəzər r.",
      parts: [
        "Binə",
        "Buzovna",
        "Dübəndi",
        "Gürgən",
        "Qala",
        "Mərdəkan",
        "Şağan",
        "Şimal DRES",
        "Şüvəlan",
        "Türkan",
        "Zirə",
      ],
    },
    {
      mainArea: "Qaradağ r.",
      parts: [
        "Ələt",
        "Qızıldaş",
        "Qobustan",
        "Lökbatan",
        "Müşfiqabad",
        "Puta",
        "Sahil",
        "Səngəçal",
        "Şubani",
      ],
    },
    {
      mainArea: "Nərimanov r.",
      parts: ["Böyükşor"],
    },
    {
      mainArea: "Nəsimi r.",
      parts: [
        "1-ci mikrorayon",
        "2-ci mikrorayon",
        "3-cü mikrorayon",
        "4-cü mikrorayon",
        "5-ci mikrorayon",
        "Kubinka",
      ],
    },
    {
      mainArea: "Nizami r.",
      parts: ["8-ci kilometr", "Keşlə"],
    },
    {
      mainArea: "Pirallahı r.",
      parts: ["Pirallahı"],
    },
    {
      mainArea: "Sabunçu r.",
      parts: [
        "Albalılıq",
        "Bakıxanov",
        "Balaxanı",
        "Bilgəh",
        "Kürdəxanı",
        "Maştağa",
        "Nardaran",
        "Pirşağı",
        "Ramana",
        "Sabunçu",
        "Savalan",
        "Yeni Balaxanı",
        "Yeni Ramana",
        "Zabrat",
      ],
    },
    {
      mainArea: "Səbail r.",
      parts: ["20-ci sahə", "Badamdar", "Bayıl", "Bibi Heybət", "Şıxov"],
    },
    {
      mainArea: "Suraxanı r.",
      parts: [
        "Bahar",
        "Bülbülə",
        "Dədə Qorqud",
        "Əmircan",
        "Günəşli",
        "Hövsan",
        "Qaraçuxur",
        "Massiv A",
        "Massiv B",
        "Massiv D",
        "Massiv G",
        "Massiv V",
        "Suraxanı",
        "Şərq",
        "Yeni Günəşli",
        "Yeni Suraxanı",
        "Zığ",
      ],
    },
    {
      mainArea: "Yasamal r.",
      parts: ["Yasamal", "Yeni Yasamal"],
    },
  ];